trigger:
- main

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Azure subscription 1(a1d4ae64-5963-412b-892b-2431eb9cfa87)'
    acrName: 'acrapl2003ayoaug'
    acrUsername: 'acrapl2003ayoaug'
    acrPassword: '2ZTI5oFKwFG7sOCLcyP2AcMv3hgLCNRHkotUostbCT+ACRATPtec'
    imageToDeploy: 'acrapl2003ayoaug.azurecr.io/aspnetcorecontainer:latest'
    containerAppName: 'aca-apl2003'
    resourceGroup: 'RG1'